### ISSUE TITLE
Appveyor is failing

### ISSUE THREAD

**Issue by pydanny** [conda-forge/whichcraft-feedstock#1]
When I click on the failure and go to: https://ci.appveyor.com/project/conda-forge/whichcraft-feedstock/branch/master
![screen shot 2016-05-20 at 11 12 44 am](https://cloud.githubusercontent.com/assets/62857/15437411/d56830d8-1e7b-11e6-955c-f66894312eaa.png)

**Comment by pydanny** [comment]
This is cascading to cause problems with the Cookiecutter-feedstock.

**Comment by bollwyvl** [comment]
@pydanny looking into it!

**Comment by jakirkham** [comment]
Yeah, I saw that with your link earlier. Though it doesn't seem to be and issue now. ( https://ci.appveyor.com/project/conda-forge/whichcraft-feedstock )

**Comment by jakirkham** [comment]
Also, I see Windows packages already. ( https://anaconda.org/conda-forge/whichcraft/files )

**Comment by bollwyvl** [comment]
Was fixed, and we're `python: noarch` now... closing!
